# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# docs: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: Purge jsDelivr cache # https://jsdelivr.com/
description: Purges file cache on jsDelivr CDN side

inputs:
  url:
    description: URLs for the cache purging (string|list)
    required: true
  attempts:
    description: Retry attempts (on the request failing) (integer)
    default: '3'
    required: false

runs:
  using: node20
  main: dist/index.js

branding:
  icon: cloud-lightning
  color: orange
